### PR TITLE
refactor: mini dataset using dataset.split

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**

### CODE REVIEW

**Comment by FelixAbrahamsson** [comment]
I realized you might want to handle the case when `len(dataset) < 256`

**Comment by FelixAbrahamsson** [comment]
How about this function?
```
def mini_proportions(dataset):
    small_proportion = min(256, len(dataset)) / len(dataset)
    return dict(big=1 - small_proportion, small=small_proportion)
```

**Comment by samedii** [comment]
I think it is nice if the split is in a separate function where you can have your proportion calculated before the split

**Comment by FelixAbrahamsson** [comment]
So this then?
```python
    return dict(
        **datasets,
        **{f"mini_{name}": mini_subset(dataset) for name, dataset in datasets.items()},
    )


def mini_subset(dataset, key_column, n=256, stratify_column=None):
    small_proportion = min(256, len(dataset)) / len(dataset)
    return dataset.split(
        key_column="index",
        proportions=dict(big=1 - small_proportion, small=small_proportion),
        stratify_column="class_name",
        seed=1,
    )["small"]
```

**Comment by FelixAbrahamsson** [comment]
Maybe skip the function arguments in the template, theyre only useful if you have multiple datasets

**Comment by samedii** [comment]
Agreed. Keep it simple. But it might be nice to keep `n`

**Pull request merged**
