### PR TITLE
Jupyter guild

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**
Uncertain about dependencies we want to add. For example `jupyter_contrib_nbextensions`, `jupyterthemes` and `jupyter-tabnine`. Also maybe we want to add things to the readme about how the op works? Like, you need to run `poetry run ipython kernel install --user --name=<name>` to add your venv to jupyter

### CODE REVIEW

**Comment by samedii** [comment]
Nice! Do we want to try this out before we merge?

**Comment by FelixAbrahamsson** [comment]
I tried it out just to see that it worked the same as my test environment which it seemed to do, but feel free to test it yourselves!

**Comment by samedii** [comment]
I didn't mean that I don't think it works. I meant that we should try it out and see if we like it :slightly_smiling_face:

**Comment by FelixAbrahamsson** [comment]
Ah yes, that's a good idea ^^

**Review by samedii — APPROVED** [review]
This seems mature enough to merge now? I haven't used it but it seems like it has been an improvement for us? @FelixAbrahamsson @malyvsen

**Comment by FelixAbrahamsson** [comment]
It's been working great in neofocus :slightly_smiling_face: 
Would like to decide on which extensions etc should be in the requirements though, between
- `jupyter_contrib_nbextensions` - imo notebooks arent worth it without this
- `ipywidgets` - basically mandatory
- `jupyterthemes` - i love this but it does seem a little buggy sometimes, perhaps not include this one. I've made a fork of this that eliminates the css bugs ive found tho that we could use.
- `jupyer-tabnine` - pretty nice, but probably not include this one as default?

**Comment by FelixAbrahamsson** [comment]
I realize now though that `jupyterthemes` and `jupyter_contrib_nbextensions` is missing from the neofocus venv, yet I still have access to it when I use the guild jupyter op there. I don't know how that works but maybe it doesnt need to be in requirements them. It's really puzzling cause theyre not in my global environment either.

**Comment by malyvsen** [comment]
I don't actually need to add the IPython kernel anyway, poetry/the venv seems to take care of that for me in every project I use Jupyter in.
As for extensions, we're just 3 people (will be up to 5 sometimes), so it's all about what *we* like. I'd probably like TabNine :)

**Comment by FelixAbrahamsson** [comment]
> I don't actually need to add the IPython kernel anyway, poetry/the venv seems to take care of that for me in every project I use Jupyter in.

Ah it's probably a dependency of jupyter so it gets installed automatically :)

> As for extensions, we're just 3 people (will be up to 5 sometimes), so it's all about what _we_ like. I'd probably like TabNine :)

@samedii will have to weigh in but I think the idea is to make this into something more public, a template that other ML practitioners will want to use as well.

**Comment by samedii** [comment]
I think it's fine to have more extension that we think are "best practice" but let's avoid bloat

**Pull request merged**
