### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**
Explanation of template structure and usage

### CODE REVIEW

**Comment by samedii** [comment]
I don't think we should duplicate all this. Also should we not have the design decisions in a separate doc? E.g. design.md?

**Comment by FelixAbrahamsson** [comment]
> I don't think we should duplicate all this. Also should we not have the design decisions in a separate doc? E.g. design.md?

Where is it duplicated?

**Comment by samedii** [comment]
The instructions are duplicated here https://github.com/Aiwizo/pytorch-lantern

I prefer having pytorch-lantern as the master and letting this repo point to it

**Comment by samedii** [comment]
After looking at this some more. All of this should probably be in the main repo rather than here

I thought this was the design issues we ran into

**Review by samedii — APPROVED** [review]

**Pull request merged**
